// Seed data for the DIVELORA handbag catalog.
// `images` are filenames only — the frontend resolves them against
// /public/products/<slug>/<filename>. Drop real photography there;
// until then the UI falls back to a placeholder graphic per product.

export const products = [
  // Totes
  {
    styleCode: "1BA274-N3V2",
    slug: "structured-saffiano-tote",
    name: "Structured Saffiano Tote",
    category: "Tote",
    price: 3400,
    colorway: "Nero",
    material: "Saffiano leather, palladium hardware",
    dimensions: "34 x 27 x 14 cm",
    description:
      "A disciplined silhouette in cross-hatched saffiano leather, built to hold its shape from morning meetings to evening travel.",
    details: [
      "Saffiano leather with palladium-finish hardware",
      "Open top with interior zip pocket",
      "Detachable shoulder strap",
      "Made in Italy",
    ],
    images: ["1.jpg", "2.jpg"],
    isFeatured: true,
    isNew: true,
  },
  {
    styleCode: "1BA891-R7Q4",
    slug: "soft-nappa-shopping-tote",
    name: "Soft Nappa Shopping Tote",
    category: "Tote",
    price: 2950,
    colorway: "Talco",
    material: "Nappa leather",
    dimensions: "38 x 30 x 16 cm",
    description:
      "An unstructured tote in buttery nappa, roomy enough for a laptop and a day's essentials without losing its shape.",
    details: [
      "Supple nappa leather",
      "Dual rolled top handles",
      "Cotton twill lining with zip pocket",
      "Made in Italy",
    ],
    images: ["1.jpg"],
    isFeatured: false,
    isNew: false,
  },
  {
    styleCode: "1BA502-K1D9",
    slug: "canvas-leather-tote",
    name: "Canvas & Leather Tote",
    category: "Tote",
    price: 2200,
    colorway: "Beige / Nero",
    material: "Jacquard canvas, leather trim",
    dimensions: "36 x 28 x 15 cm",
    description:
      "Signature jacquard canvas paired with smooth leather trim, a lighter-weight tote for daily rotation.",
    details: [
      "Jacquard canvas body with leather trim",
      "Leather top handles",
      "Interior logo lining",
      "Made in Italy",
    ],
    images: [],
    isFeatured: false,
    isNew: false,
  },

  // Shoulder Bags
  {
    styleCode: "1BD127-M4T8",
    slug: "quilted-nappa-shoulder-bag",
    name: "Quilted Nappa Shoulder Bag",
    category: "Shoulder Bag",
    price: 3100,
    colorway: "Nero",
    material: "Quilted nappa leather, chain strap",
    dimensions: "26 x 18 x 8 cm",
    description:
      "Diamond-quilted nappa on a compact silhouette, carried by a slim chain-and-leather strap.",
    details: [
      "Diamond-quilted nappa leather",
      "Chain-and-leather shoulder strap",
      "Front flap with logo clasp",
      "Made in Italy",
    ],
    images: ["1.jpg", "2.jpg", "3.jpg"],
    isFeatured: true,
    isNew: false,
  },
  {
    styleCode: "1BD350-H2W1",
    slug: "pebbled-leather-hobo",
    name: "Pebbled Leather Hobo",
    category: "Shoulder Bag",
    price: 2650,
    colorway: "Cognac",
    material: "Pebbled calfskin",
    dimensions: "30 x 24 x 10 cm",
    description:
      "A soft, slouched hobo in grained calfskin that softens with wear, sized for everything but the essentials.",
    details: [
      "Pebbled calfskin leather",
      "Single top shoulder strap",
      "Magnetic snap closure",
      "Made in Italy",
    ],
    images: [],
    isFeatured: false,
    isNew: true,
  },
  {
    styleCode: "1BD214-C6L3",
    slug: "chain-shoulder-bag",
    name: "Chain Shoulder Bag",
    category: "Shoulder Bag",
    price: 2900,
    colorway: "Nero",
    material: "Smooth calfskin, gold hardware",
    dimensions: "24 x 16 x 7 cm",
    description: "A precise structured shoulder bag anchored by a substantial gold curb chain.",
    details: ["Smooth calfskin leather", "Gold-tone curb chain strap", "Turn-lock closure", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },
  {
    styleCode: "1BD466-S9F0",
    slug: "saffiano-flap-shoulder-bag",
    name: "Saffiano Flap Shoulder Bag",
    category: "Shoulder Bag",
    price: 2750,
    colorway: "Cipria",
    material: "Saffiano leather",
    dimensions: "22 x 15 x 7 cm",
    description: "A clean flap silhouette in structured saffiano, sized for the essentials only.",
    details: ["Saffiano leather", "Adjustable shoulder strap", "Front flap, magnetic closure", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },

  // Top Handle
  {
    styleCode: "1BA144-G8V6",
    slug: "galleria-top-handle",
    name: "Galleria Top-Handle",
    category: "Top Handle",
    price: 3900,
    colorway: "Nero",
    material: "Saffiano leather, palladium hardware",
    dimensions: "28 x 20 x 14 cm",
    description:
      "Born from an archival sketch, the house's signature top-handle returns in supple Re-Nappa leather and a new saffiano weave — a study in structure and ease carried by hand since 1913.",
    details: [
      "Saffiano leather with Re-Nappa panels",
      "Double rolled top handles",
      "Detachable shoulder strap included",
      "Made in Italy",
    ],
    images: ["1.jpg", "2.jpg"],
    isFeatured: true,
    isNew: false,
  },
  {
    styleCode: "1BA333-D5R2",
    slug: "structured-box-top-handle",
    name: "Structured Box Top-Handle",
    category: "Top Handle",
    price: 3600,
    colorway: "Avorio",
    material: "Box calfskin",
    dimensions: "20 x 15 x 9 cm",
    description: "A rigid, architectural box bag in smooth calfskin with a single sculpted handle.",
    details: ["Box calfskin leather", "Sculpted single top handle", "Suede lining", "Made in Italy"],
    images: [],
    isFeatured: true,
    isNew: true,
  },
  {
    styleCode: "1BA778-P3N7",
    slug: "mini-top-handle",
    name: "Mini Top-Handle",
    category: "Top Handle",
    price: 2400,
    colorway: "Nero",
    material: "Saffiano leather",
    dimensions: "16 x 12 x 7 cm",
    description: "The Galleria silhouette scaled down to a mini proportion for evening.",
    details: ["Saffiano leather", "Top handle with removable strap", "Logo-engraved hardware", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },

  // Crossbody
  {
    styleCode: "1BH038-Y1K4",
    slug: "saffiano-crossbody",
    name: "Saffiano Crossbody",
    category: "Crossbody",
    price: 1950,
    colorway: "Nero",
    material: "Saffiano leather",
    dimensions: "19 x 13 x 5 cm",
    description: "A slim, structured crossbody in saffiano leather sized for phone, cards and keys.",
    details: ["Saffiano leather", "Adjustable crossbody strap", "Zip closure", "Made in Italy"],
    images: ["1.jpg"],
    isFeatured: false,
    isNew: false,
  },
  {
    styleCode: "1BH512-Z8B1",
    slug: "re-nylon-crossbody",
    name: "Re-Nylon Crossbody",
    category: "Crossbody",
    price: 1650,
    colorway: "Nero",
    material: "Regenerated Re-Nylon, leather trim",
    dimensions: "21 x 15 x 6 cm",
    description:
      "Regenerated nylon in a lightweight crossbody shape — part of the house's ongoing shift to responsibly sourced materials.",
    details: ["Regenerated Re-Nylon", "Leather trim and strap", "Front zip pocket", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: true,
  },
  {
    styleCode: "1BH290-A4X5",
    slug: "quilted-camera-bag",
    name: "Quilted Camera Bag",
    category: "Crossbody",
    price: 2100,
    colorway: "Cipria",
    material: "Quilted nappa leather",
    dimensions: "18 x 12 x 8 cm",
    description: "A compact quilted camera-bag shape with a structured base and a long adjustable strap.",
    details: ["Quilted nappa leather", "Long adjustable crossbody strap", "Front flap pocket", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },
  {
    styleCode: "1BH607-E2M9",
    slug: "leather-pouch-crossbody",
    name: "Leather Pouch Crossbody",
    category: "Crossbody",
    price: 1450,
    colorway: "Cognac",
    material: "Smooth calfskin",
    dimensions: "20 x 14 x 4 cm",
    description: "A flat pouch silhouette on a thin crossbody strap, minimal and unlined for everyday carry.",
    details: ["Smooth calfskin leather", "Thin adjustable strap", "Zip-top closure", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },

  // Mini Bags
  {
    styleCode: "1BH955-W6C3",
    slug: "chain-mini-bag",
    name: "Chain Mini Bag",
    category: "Mini Bag",
    price: 2900,
    colorway: "Nero",
    material: "Quilted nappa leather, gold chain",
    dimensions: "15 x 10 x 5 cm",
    description: "A mini quilted bag on a slim gold chain — scaled for evening, built with full-size hardware.",
    details: ["Quilted nappa leather", "Gold-tone chain strap", "Turn-lock closure", "Made in Italy"],
    images: ["1.jpg"],
    isFeatured: true,
    isNew: false,
  },
  {
    styleCode: "1BA612-T3J8",
    slug: "micro-top-handle",
    name: "Micro Top-Handle",
    category: "Mini Bag",
    price: 2100,
    colorway: "Avorio",
    material: "Saffiano leather",
    dimensions: "12 x 9 x 6 cm",
    description: "The house's top-handle silhouette at its smallest scale, more object than bag.",
    details: ["Saffiano leather", "Micro top handle", "Removable strap", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },
  {
    styleCode: "1BH803-L5N1",
    slug: "mini-saffiano-pouch",
    name: "Mini Saffiano Pouch",
    category: "Mini Bag",
    price: 990,
    colorway: "Nero",
    material: "Saffiano leather",
    dimensions: "13 x 8 x 3 cm",
    description: "A flat mini pouch with a wrist strap, sized for cards and a phone.",
    details: ["Saffiano leather", "Detachable wrist strap", "Zip closure", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },

  // Clutches
  {
    styleCode: "1BF221-V7H4",
    slug: "satin-evening-clutch",
    name: "Satin Evening Clutch",
    category: "Clutch",
    price: 1850,
    colorway: "Nero",
    material: "Duchesse satin, crystal clasp",
    dimensions: "22 x 12 x 3 cm",
    description: "A flat satin clutch finished with a crystal-embellished clasp, made for evening.",
    details: ["Duchesse satin", "Crystal-embellished clasp", "Detachable chain strap", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: true,
  },
  {
    styleCode: "1BF467-X2Q6",
    slug: "saffiano-envelope-clutch",
    name: "Saffiano Envelope Clutch",
    category: "Clutch",
    price: 1400,
    colorway: "Cipria",
    material: "Saffiano leather",
    dimensions: "24 x 14 x 2 cm",
    description: "A structured envelope clutch in saffiano leather with a triangular logo plaque.",
    details: ["Saffiano leather", "Envelope flap closure", "Interior card slots", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },
  {
    styleCode: "1BF890-U9D2",
    slug: "leather-wristlet-pouch",
    name: "Leather Wristlet Pouch",
    category: "Clutch",
    price: 890,
    colorway: "Nero",
    material: "Smooth calfskin",
    dimensions: "20 x 11 x 3 cm",
    description: "A slim wristlet pouch in smooth calfskin, the everyday companion to a larger bag.",
    details: ["Smooth calfskin leather", "Wrist strap", "Zip closure", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },

  // Travel
  {
    styleCode: "1BZ044-F1S8",
    slug: "leather-weekender",
    name: "Leather Weekender",
    category: "Travel",
    price: 4600,
    colorway: "Cognac",
    material: "Full-grain calfskin",
    dimensions: "50 x 30 x 22 cm",
    description: "A full-grain calfskin weekender built for the overhead bin, with a dedicated shoe compartment.",
    details: ["Full-grain calfskin leather", "Dedicated shoe compartment", "Detachable, adjustable strap", "Made in Italy"],
    images: [],
    isFeatured: true,
    isNew: false,
  },
  {
    styleCode: "1BZ298-J6P0",
    slug: "re-nylon-duffle",
    name: "Re-Nylon Duffle",
    category: "Travel",
    price: 2800,
    colorway: "Nero",
    material: "Regenerated Re-Nylon, leather trim",
    dimensions: "48 x 28 x 24 cm",
    description: "A lightweight duffle in regenerated nylon, structured enough for a week away.",
    details: ["Regenerated Re-Nylon", "Leather carry handles and trim", "Interior zip pocket", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: true,
  },
  {
    styleCode: "1BZ511-B4Y3",
    slug: "garment-carry-on",
    name: "Garment Carry-On",
    category: "Travel",
    price: 5200,
    colorway: "Nero",
    material: "Saffiano leather, aluminum frame",
    dimensions: "54 x 40 x 20 cm",
    description: "A structured carry-on in saffiano leather over an aluminum frame, built for the ateliers' standard of travel.",
    details: ["Saffiano leather over aluminum frame", "Full garment compartment", "Telescopic handle", "Made in Italy"],
    images: [],
    isFeatured: false,
    isNew: false,
  },
];
