// Static demo catalogue — used as a fallback throughout src/lib/api.js
// whenever the real /api backend is unreachable (e.g. no server deployed
// yet in production), so the site always has something to show instead of
// blank/broken pages. Shaped to match the real Product model exactly.

export const DEMO_PRODUCTS = [
  {
    id: 1,
    slug: "structured-saffiano-tote",
    styleCode: "DVL-0101",
    name: "Structured Saffiano Tote",
    category: "Tote",
    price: 2150,
    currency: "USD",
    colorway: "Nero",
    material: "Saffiano leather, palladium hardware, suede lining.",
    dimensions: '15" W x 11" H x 6" D',
    description:
      "A structured tote in crosshatched saffiano leather, built for the everyday carry of a working wardrobe.",
    details: ["Hand-cut and stitched in Milan", "Zip-top closure", "Interior zip and slip pockets", "Protective dust bag included"],
    images: ["1.jpg"],
    isFeatured: true,
    isNew: false,
  },
  {
    id: 2,
    slug: "pebbled-leather-hobo",
    styleCode: "DVL-0102",
    name: "Pebbled Leather Hobo",
    category: "Shoulder Bag",
    price: 1890,
    currency: "USD",
    colorway: "Cognac",
    material: "Pebbled calfskin, brass hardware, suede lining.",
    dimensions: '13" W x 10" H x 4" D',
    description: "A soft-structured hobo in richly grained leather that only improves with wear.",
    details: ["Hand-cut and stitched in Milan", "Adjustable shoulder strap", "Magnetic snap closure", "Protective dust bag included"],
    images: ["1.jpg"],
    isFeatured: true,
    isNew: false,
  },
  {
    id: 3,
    slug: "galleria-top-handle",
    styleCode: "DVL-0142",
    name: "Galleria Top-Handle",
    category: "Top Handle",
    price: 2450,
    currency: "USD",
    colorway: "Cognac",
    material: "Full-grain Italian calfskin, brass hardware, suede lining.",
    dimensions: '11" W x 8" H x 4.5" D',
    description:
      "Born from an archival sketch, the Galleria returns this season in supple leather — a study in structure and ease carried by hand since 1913.",
    details: [
      "Hand-cut and stitched in Milan",
      "Detachable, adjustable shoulder strap",
      "Interior zip and slip pockets",
      "Protective dust bag included",
    ],
    images: ["1.jpg"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: 4,
    slug: "canvas-leather-tote",
    styleCode: "DVL-0118",
    name: "Canvas & Leather Crossbody",
    category: "Crossbody",
    price: 1290,
    currency: "USD",
    colorway: "Ecru / Tobacco",
    material: "Waxed canvas body, leather trim, antique brass hardware.",
    dimensions: '9" W x 7" H x 3" D',
    description: "A relaxed crossbody pairing house canvas with leather trim — light enough for all-day wear.",
    details: ["Hand-cut and stitched in Milan", "Adjustable crossbody strap", "Front flap pocket", "Protective dust bag included"],
    images: ["1.jpg"],
    isFeatured: false,
    isNew: true,
  },
  {
    id: 5,
    slug: "mini-top-handle",
    styleCode: "DVL-0155",
    name: "Mini Top-Handle",
    category: "Mini Bag",
    price: 1650,
    currency: "USD",
    colorway: "Rosa",
    material: "Nappa leather, gold-tone hardware, suede lining.",
    dimensions: '7" W x 5.5" H x 3" D',
    description: "The Galleria silhouette scaled down — a compact top-handle for evenings out.",
    details: ["Hand-cut and stitched in Milan", "Detachable chain strap", "Single interior pocket", "Protective dust bag included"],
    images: ["1.jpg"],
    isFeatured: false,
    isNew: false,
  },
  {
    id: 6,
    slug: "leather-wristlet-pouch",
    styleCode: "DVL-0167",
    name: "Leather Wristlet Pouch",
    category: "Clutch",
    price: 690,
    currency: "USD",
    colorway: "Nero",
    material: "Nappa leather, gold-tone hardware.",
    dimensions: '9" W x 5" H x 1.5" D',
    description: "A slim wristlet pouch for the essentials — equally at home day or night.",
    details: ["Hand-cut and stitched in Milan", "Detachable wrist strap", "Zip closure", "Protective dust bag included"],
    images: ["1.jpg"],
    isFeatured: false,
    isNew: false,
  },
  {
    id: 7,
    slug: "soft-nappa-shopping-tote",
    styleCode: "DVL-0178",
    name: "Soft Nappa Shopping Tote",
    category: "Travel",
    price: 2290,
    currency: "USD",
    colorway: "Talpa",
    material: "Soft nappa leather, brass hardware, canvas lining.",
    dimensions: '18" W x 12" H x 7" D',
    description: "An oversized soft-structure tote built for travel days and weekend escapes.",
    details: ["Hand-cut and stitched in Milan", "Rolled top-handles", "Interior zip pocket", "Protective dust bag included"],
    images: ["1.jpg"],
    isFeatured: true,
    isNew: false,
  },
  {
    id: 8,
    slug: "structured-box-top-handle",
    styleCode: "DVL-0189",
    name: "Structured Box Top-Handle",
    category: "Top Handle",
    price: 2350,
    currency: "USD",
    colorway: "Avorio",
    material: "Box calf leather, palladium hardware, suede lining.",
    dimensions: '9" W x 6.5" H x 4" D',
    description: "A precise, architectural box-top handle in smooth box calf — the house's most sculptural shape.",
    details: ["Hand-cut and stitched in Milan", "Rigid top handle", "Detachable shoulder strap", "Protective dust bag included"],
    images: ["1.jpg"],
    isFeatured: false,
    isNew: true,
  },
];

export const DEMO_CATEGORIES = [
  "Tote",
  "Shoulder Bag",
  "Top Handle",
  "Crossbody",
  "Mini Bag",
  "Clutch",
  "Travel",
].map((category) => ({
  category,
  count: DEMO_PRODUCTS.filter((p) => p.category === category).length,
}));
